//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _05.StringInString.ConsoleClient.ServiceReferenceStringInString {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceStringInString.IStringInString")]
    public interface IStringInString {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringInString/GetOccuranceCount", ReplyAction="http://tempuri.org/IStringInString/GetOccuranceCountResponse")]
        int GetOccuranceCount(string searched, string container);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringInString/GetOccuranceCount", ReplyAction="http://tempuri.org/IStringInString/GetOccuranceCountResponse")]
        System.Threading.Tasks.Task<int> GetOccuranceCountAsync(string searched, string container);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringInStringChannel : _05.StringInString.ConsoleClient.ServiceReferenceStringInString.IStringInString, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringInStringClient : System.ServiceModel.ClientBase<_05.StringInString.ConsoleClient.ServiceReferenceStringInString.IStringInString>, _05.StringInString.ConsoleClient.ServiceReferenceStringInString.IStringInString {
        
        public StringInStringClient() {
        }
        
        public StringInStringClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringInStringClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringInStringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringInStringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetOccuranceCount(string searched, string container) {
            return base.Channel.GetOccuranceCount(searched, container);
        }
        
        public System.Threading.Tasks.Task<int> GetOccuranceCountAsync(string searched, string container) {
            return base.Channel.GetOccuranceCountAsync(searched, container);
        }
    }
}
